### ISSUE TITLE
more flexbox

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#13]
it needs more flexbox according to:
![image](https://user-images.githubusercontent.com/40470736/81707978-3d5de380-9471-11ea-9c7b-316d49bd1e4f.png)

https://www.internetingishard.com/html-and-css/flexbox/
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

so hopefully this issue will remind me to do this later

**Comment by easrng** [comment]
I'm adding much more flexbox.

**Comment by jeffalo** [comment]
> I'm adding much more flexbox.

thats awesome, but if you make a pr for it, would it be the whole fork that you're making or just the flexbox? i rather just merge the standalone flexbox changes instead of the whole fork if you dont mind :)

**Comment by easrng** [comment]
Well, that would be hard, because I restructured the sidebar, and for that you'd need to re-implement or copy some JS too, but I sent the whole thing.

**Comment by jeffalo** [comment]
aded
