### ISSUE TITLE
load note from url

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#14]
should be as simple as changing the upload button to ask file or url and if url do a get request and make a new note using that as the response

**Comment by easrng** [comment]
In progress, kinda.

**Comment by easrng** [comment]
I wrote a Google apps script backend for storing shared notes.

**Comment by jeffalo** [comment]
yeah i saw your fork, it looks really cool, but most of the changes probably aren't things i'd merge to this main repo.  (eg. the backend stuff seems a bit too complex for this simple webapp), but keep devloping your fork its really cool  :)

**Comment by easrng** [comment]
It's not very complicated. Other than the hashing algorithm, the backend is only
```js
let routes={
  save({text}){
    let props=PropertiesService.getScriptProperties()
    let id=hash(text)
    props.setProperty(id, text)
    return {
      id
    }
  },
  get({id}){
    let props=PropertiesService.getScriptProperties()
    let text=props.getProperty(id)||"Invalid ID"
    return {text}
  }
}
```
with a little extra to call the routes. It's pretty simple.

**Comment by easrng** [comment]
The code is at https://script.google.com/d/1EGykuWdJfli0i-zm1V_zGK-v9tRwS2rGPwD_7RaRYk8quQ2kjUxv2Oqq/edit?usp=sharing

**Comment by easrng** [comment]
Most of the complexity is JSONP code to avoid running into CORS.

**Comment by easrng** [comment]
This would require a proxy, right?

**Comment by jeffalo** [comment]
im not sure

**Comment by easrng** [comment]
we could use cors-anywhere, but they are sometimes slow. Also, how would this handle HTML?

**Comment by jeffalo** [comment]
oh this seems like it might be too much hassle for little result (since copying and pasting is a thing)
