### ISSUE TITLE
confusing design

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#20]
right now, we have a download button with the icon of a save button, this gets people thinking that there is no autosave.

i have two solutions to fix this,

#1 replace save icon with download

#2 (the better one) remove the save button from the actions and add a custom context menu for when someone right clicks on a file. this would have another way to acess the rename and delete buttons and also have a download button. 

^ i'm not sure how to make a custom context menu, but im sure i can find it on google

**Comment by mxmou** [comment]
> ^ i'm not sure how to make a custom context menu, but im sure i can find it on google

You can listen for `"contextmenu"` events and call `event.preventDefault()`. Then show an element with `position: fixed` at mouse position.

**Comment by jeffalo** [comment]
aha thanks :)

**Comment by jeffalo** [comment]
done in newest commit
