### ISSUE TITLE
long file name

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#23]
if a file has a really long file name, it doesn't make a new line and it makes the navbar like 1 px wide.

idk how flexbox works and i think this needs help

**Comment by jeffalo** [comment]
![image](https://user-images.githubusercontent.com/40470736/82091398-9048cc80-96f7-11ea-93d6-270f6049eddc.png)

**Comment by jeffalo** [comment]
fix:
basically keep navbar a constant size and perhaps if a file title is too long, make new lines instead of going off screen.

css is wack and i dont understand

**Comment by jeffalo** [comment]
aparently remove `overflow-x` is fix

**Comment by mxmou** [comment]
Isn't this fixed?

**Comment by jeffalo** [comment]
this has been fixed but if some wack css thing happens and idk what to do i should keep this open for a weekend incase i notice something weird

**Comment by jeffalo** [comment]
nothing wack has happened so far, so i'm closing this issue
