### ISSUE TITLE
when file is renamed a toast saying it was deleted shows up

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#24]
easy fix, i can do it, i just need to pass a parameter when deleting a file

just a reminder to fix this

**Comment by jeffalo** [comment]
~~this has been fixed but if some wack css thing happens and idk what to do i should keep this open for a weekend incase i notice something weird~~

**Comment by mxmou** [comment]
> this has been fixed but if some wack css thing happens and idk what to do i should keep this open for a weekend incase i notice something weird

No, it wasn't fixed. The other bug was fixed.

**Comment by jeffalo** [comment]
oh oops wrong issue lol

**Comment by jeffalo** [comment]
fixed
