### ISSUE TITLE
Flex box the sidenav

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/noted#8]
Currently, the sidenav is not flexbox, which makes it a pain to work with. 

perhaps i can make it into a flex box or something? im not really good with css so someone please help

this will also help with mobile layout

**Comment by JeffaloBob** [comment]
this might have to be changed into flex box or somethng i hate css please someone help

**Comment by mxmou** [comment]
So you want the sidenav to be a flex container? Can you explain how this would help with mobile layout?

**Comment by jeffalo** [comment]
well, right now the solution i'm doing for the sidenav is not really easy to work with, so i'd imagine using a flex container it would be easier to modify sizing based on the screen size and it'd be more responsive than using what i'm using right now.

but i could be wrong im not that good with css 🤣

**Comment by mxmou** [comment]
OK. It looks like making individual items flex containers might be a better idea - then it would be easier to truncate long file names.

**Comment by jeffalo** [comment]
@mxmou ah ok. i don't really understand all this flex stuff.

**Comment by jeffalo** [comment]
@mxmou heres a mockup i made, would this be correct?
![image](https://user-images.githubusercontent.com/40470736/81664759-1509c100-9440-11ea-9758-bd17e6cba28f.png)

**Comment by mxmou** [comment]
@JeffaloBob Yes. Actually I'm working on this right now.

**Comment by jeffalo** [comment]
> @JeffaloBob Yes. Actually I'm working on this right now.

ah thanks :)
